// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $streams: i.entity({
      abortReason: i.string().optional(),
      clientId: i.string().unique().indexed(),
      done: i.boolean().optional(),
      size: i.number().optional(),
    }),
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      type: i.string().optional(),
    }),
    alumnos: i.entity({
      activo_en_rutas: i.any().optional(),
      colegio_id: i.any().optional(),
      created_at: i.any().optional(),
      cuota_mensual: i.number().optional(),
      dias_ruta: i.any().optional(),
      direccion_recogida: i.any().optional(),
      grado: i.any().optional(),
      hermano_ids: i.any().optional(),
      lat: i.any().optional(),
      lng: i.any().optional(),
      modalidad_servicio: i.any().optional(),
      nombre: i.any().optional(),
      notas_medicas: i.any().optional(),
      representante_id: i.any().optional(),
      tiempo_abordaje_estimado_min: i.any().optional(),
    }),
    colegios: i.entity({
      contacto_telefono: i.any().optional(),
      created_at: i.any().optional(),
      direccion: i.any().optional(),
      hora_llegada_limite: i.any().optional(),
      lat: i.any().optional(),
      lng: i.any().optional(),
      nombre: i.any().optional(),
    }),
    conductores: i.entity({
      activo: i.any().optional(),
      capacidad_pasajeros: i.any().optional(),
      created_at: i.any().optional(),
      email: i.any().optional(),
      foto_url: i.any().optional(),
      licencia: i.any().optional(),
      nombre: i.any().optional(),
      telefono: i.any().optional(),
      vehiculo_modelo: i.any().optional(),
      vehiculo_placa: i.any().optional(),
    }),
    eventos_ruta: i.entity({
      alumno_id: i.any().optional(),
      alumno_nombre: i.any().optional(),
      colegio_id: i.any().optional(),
      colegio_nombre: i.any().optional(),
      conductor_id: i.any().optional(),
      conductor_nombre: i.any().optional(),
      created_at: i.any().optional(),
      detalle_json: i.any().optional(),
      estado_anterior: i.any().optional(),
      estado_nuevo: i.any().optional(),
      evento: i.any().optional(),
      fecha_ruta: i.any().optional(),
      hora_evento: i.any().optional(),
      orden_parada: i.any().optional(),
      parada_id: i.any().optional(),
      ruta_id: i.any().optional(),
    }),
    pagos: i.entity({
      alumno_id: i.string(),
      concepto: i.string().optional(),
      created_at: i.string().optional(),
      estado: i.string(),
      fecha_pago: i.string(),
      mes_cobrado: i.string(),
      metodo_pago: i.string(),
      monto: i.number(),
      notas: i.string().optional(),
      representante_id: i.string(),
    }),
    paradas_ruta: i.entity({
      alumno_id: i.any().optional(),
      created_at: i.any().optional(),
      distancia_desde_anterior_km: i.any().optional(),
      estado: i.any().optional(),
      hora_estimada: i.any().optional(),
      hora_real: i.any().optional(),
      lat: i.any().optional(),
      lng: i.any().optional(),
      orden: i.any().optional(),
      ruta_id: i.any().optional(),
      tiempo_desde_anterior_min: i.any().optional(),
    }),
    representantes: i.entity({
      created_at: i.any().optional(),
      email: i.any().optional(),
      magic_token: i.any().optional(),
      nombre: i.any().optional(),
      telefono_whatsapp: i.any().optional(),
    }),
    rutas_diarias: i.entity({
      colegio_id: i.any().optional(),
      conductor_id: i.any().optional(),
      created_at: i.any().optional(),
      dia_semana: i.any().optional(),
      distancia_total_km: i.any().optional(),
      estado: i.any().optional(),
      fecha: i.any().optional(),
      hora_llegada_deseada: i.any().optional(),
      hora_llegada_estimada: i.any().optional(),
      hora_llegada_objetivo: i.any().optional(),
      hora_llegada_real: i.any().optional(),
      hora_salida_deseada: i.any().optional(),
      hora_salida_estimada: i.any().optional(),
      hora_salida_real: i.any().optional(),
      horario_valido: i.any().optional(),
      modo_optimizacion: i.any().optional(),
      origen_direccion: i.any().optional(),
      origen_lat: i.any().optional(),
      origen_lng: i.any().optional(),
      polyline_json: i.any().optional(),
      tiempo_abordaje_por_alumno_min: i.any().optional(),
      tiempo_abordaje_total_min: i.any().optional(),
      tiempo_manejo_estimado_min: i.any().optional(),
      tiempo_total_estimado_min: i.any().optional(),
      tipo_trayecto: i.any().optional(),
      tramos_elegidos_json: i.any().optional(),
      variante: i.any().optional(),
    }),
    tracking_logs: i.entity({
      lat: i.any().optional(),
      lng: i.any().optional(),
      rumbo_grados: i.any().optional(),
      ruta_id: i.any().optional(),
      timestamp: i.any().optional(),
      velocidad_kmh: i.any().optional(),
    }),
    usuarios: i.entity({
      created_at: i.any().optional(),
      email: i.any().optional(),
      nombre: i.any().optional(),
      rol: i.any().optional(),
    }),
    webhook_logs: i.entity({
      created_at: i.any().optional(),
      duracion_ms: i.any().optional(),
      estado_envio: i.any().optional(),
      evento: i.any().optional(),
      http_status: i.any().optional(),
      intentos: i.any().optional(),
      payload_json: i.any().optional(),
      timestamp: i.any().optional(),
      url_destino: i.any().optional(),
    }),
  },
  links: {
    $streams$files: {
      forward: {
        on: "$streams",
        has: "many",
        label: "$files",
      },
      reverse: {
        on: "$files",
        has: "one",
        label: "$stream",
        onDelete: "cascade",
      },
    },
    $usersLinkedPrimaryUser: {
      forward: {
        on: "$users",
        has: "one",
        label: "linkedPrimaryUser",
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "many",
        label: "linkedGuestUsers",
      },
    },
  },
  rooms: {},
});

// This helps TypeScript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
